docs: Add Heroku tutorial [wip]
itsolschool/itsolschool.github.io pull request #137
Opened 2019-01-01 17:02 UTC by BANOnotIT

2019-01-01 17:56 UTC, mreluzeon commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через ENV. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки брать
не сюда

2019-01-01 17:56 UTC, mreluzeon commented on tutorial/heroku_deployment.md
> +Ещё можно запускать worker процессы - которые будут работать постоянно. Но эти процессы **будут так же есть часы в месяц**, которые можно было использовать для работы основного приложения. Поэтому эт
в конец

2019-01-01 17:56 UTC, mreluzeon commented on tutorial/heroku_deployment.md
> +Так же платформа позволяет [выполнять какие-то команды по расписанию](https://devcenter.heroku.com/articles/scheduler). Вещь работает достаточно стабильно, хотя сами **разработчики предупреждают**, ч
в конец

2019-01-01 17:56 UTC, mreluzeon commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Closure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
Closure - замыкания
Clojure - язык программирования

2019-01-01 17:56 UTC, mreluzeon commented on tutorial/heroku_deployment.md
> +- [Firebase](https://firebase.google.com/) - Платформа, которая даёт свой времворк для взаимодействия. Если вы знаете что такое VM или какой-нибудь Node.js, то по сути вы просто пишите код для этой п
"времворк" опечатка

2019-01-01 18:00 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Firebase](https://firebase.google.com/) - Платформа, которая даёт свой времворк для взаимодействия. Если вы знаете что такое VM или какой-нибудь Node.js, то по сути вы просто пишите код для этой п
```suggestion
- [Firebase](https://firebase.google.com/) - Платформа, которая даёт свой фремворк для взаимодействия. Если вы знаете что такое VM или какой-нибудь Node.js, то по сути вы просто пишите код для этой платформы и он просто вызывается тогда, когда это надо, без лишних прогреваний или запуска виртуального сервера. _Оплата по количеству запросов_.
```

2019-01-01 18:01 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Closure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
```suggestion
Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Clojure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относительно экзотическое, например MySQL базу данных или RabbitMQ очередь для своего проекта. Ну или, например, C++ среду для какой-то своей очень очень ресурсоёмкой задачи.
```

2019-01-01 18:12 UTC, magicwolf9 requested changes

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +И так. Начнём с того, что такое облако. Облако - большое количество серверов, которыми занимается кто-то другой. Вам же на этих серверах можно делать что-то, что хотите сами, но по строгим правилам л
"какого-ниудь Tor"
```suggestion
 И так. Начнём с того, что такое облако. Облако - большое количество серверов, которыми занимается кто-то другой. Вам же на этих серверах можно делать что-то, что хотите сами, но по строгим правилам лицензирования. Например если владелец серверов не хочет иметь проблем с ФСБ, он может просто не разрешать использовать свои сервера для создания проксей Телеграма или какого-нибудь Tor. Но это уже политика...
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощьности или время
```suggestion
 Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощности, или время работы на этих процессорах, или диски определённого объёма. Нам не нужно ничего самим трогать и думать о физической составляющей - этим занимается хостер. Даже больше того, вы можете сказать: "Мне сегодня понадобятся 300 серверов, потому что сегодня будет праздник", и хостер в автоматическом режиме просто отдаст вам 300 серверов.
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +### Чем это отличается от VDS?
Что такое VDS?

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +- [Heroku](https://heroku.com) - Обёртка над AWS. Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле Procfile как именно ваше приложение можно запу
Что такое AWS?

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +1. Бесплатно: 570 часов работы каждый месяц (19 часов/день), 10k строчек в БД (Postgree) и Redis - достаточно неплохо для школьного проекта
```suggestion
 1. Бесплатно: 570 часов работы каждый месяц (19 часов/день), 10k строчек в БД (Postgree) и Redis - достаточно неплохо для небольшого проекта
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Closure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
Что такое "пресет"?

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Но для нас вполне хватит Python + Postgree + Redis, остальное в проектах ШИР не встречается)
```suggestion
 Но часто вполне хватает Python + Postgree + Redis.
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +2. Первые 3 поля - обязательные для честного заполнения. Остальное - для статистики внутри хероку. Но компанией вы моежет назвать свою команду, себя представить студентом, а любимый язык выбрать по в
```suggestion
 2. Первые 3 поля - обязательные для честного заполнения. Остальное - для статистики внутри хероку. Но компанией вы можете назвать свою команду, себя представить студентом, а любимый язык выбрать по вкусу.
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Способов передачи приложения серверам хероку очень много - и ручные, и специальные git репозитории, и Docker образа. Нам всё это не интересно, потому что это всё сложные технологии для бородатых дяде
```suggestion
 Способов передачи приложения серверам хероку очень много - и ручные, и специальные git репозитории, и Docker образы. Нам всё это не интересно, потому что это всё сложные технологии для бородатых дядек, которые едят на завтрак материнские платы, запивая смуззи из пива.
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
Консольные команды для создания файла вообще такое себе, лучше gui инструкцию со скринами

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +web: gunicorn app:flask_app --log-file=- --log-level=debug
Все это лучше скринами из того же PyCharm

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Эта строчка может меняться. В зависимости от того как захочет Heroku, может через день, может через неделю, а может им понадобится менять её хоть каждые 5 минут. Поэтому нам не важна сама строчка, на
```suggestion
 Эта строчка может меняться. В зависимости от того как захочет Heroku, может через день, может через неделю, а может им понадобится менять её хоть каждые 5 минут. Поэтому нам не важна сама строчка, нам эта строчка нужна внутри приложения.
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Всё! Теперь мы умеем забирать настройки для приложения из переменных окружения.
Переменные окружения нужно пояснить, непонятно что это за зверь

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +2. Поиграйтесь немного с тем, что найдёте в интерфейсе Heroku. Например вы можете полностью удалить все данные в БД, посмтреть логи своего приложения, использовать вместо appname.herokuapp.com свой с
```suggestion
 2. Поиграйтесь немного с тем, что найдёте в интерфейсе Heroku. Например вы можете полностью удалить все данные в БД, посмотреть логи своего приложения, использовать вместо appname.herokuapp.com свой собственный домен, вручную достать исходники из GitHub или принудительно перезапустить приложение.
```

2019-01-01 18:12 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Так же вы можете [почитать документацию на английском](https://devcenter.heroku.com/), [обратиться к Хелпдеску за помощью](https://itsolschool.slack.com/messages/helpdesk) или [посмотреть на исходник
Ты говорил, что у хероку есть какое-то клевое видео с объяснениями и без слов, вот его сюда хорошо бы

2019-01-01 18:40 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощьности или время
А что тут изменить надо?

2019-01-01 18:40 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через ENV. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки брать
А куда эту часть добавить?

2019-01-01 18:40 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
Жень. Нет GUI к pip. В принципе в питоне нет ничего графического, кроме IDLE

2019-01-01 18:40 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +web: gunicorn app:flask_app --log-file=- --log-level=debug
Эмм, а что не понятно то сейчас? Что конкретно ты хочешь исправить с помощью PC?

2019-01-01 18:40 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Так же вы можете [почитать документацию на английском](https://devcenter.heroku.com/), [обратиться к Хелпдеску за помощью](https://itsolschool.slack.com/messages/helpdesk) или [посмотреть на исходник
Вообще да, неплохо было бы, но. Это видео рассказывает о том, как деплоить с помощью git репозитория на самом heroku. В этой инструкции рассказывается о интеграции с GitHub. Кстати это надо бы внести в плюсы.

2019-01-01 18:42 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Heroku](https://heroku.com) - Обёртка над AWS. Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле Procfile как именно ваше приложение можно запу
Ты думаешь нужно прямо сразу давать им сокращение в предыдущей строчке?

2019-01-01 18:45 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
И pip freeze - команда как раз для создания requirements.txt. Так что эта команда вполне оправдана. А учитывая, что никаким другим образом получить такой файл нельзя нормально, то лучше оставить как есть.

2019-01-01 18:53 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Amazon Web Services](https://aws.amazon.com/ru/) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и сколько чего
```suggestion
- [Amazon Web Services](https://aws.amazon.com/ru/) (AWS) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и сколько чего развернуть. _Оплата по времени работы и объёму*время хранения данных в хранилищах_.
```
@magicwolf9 вот так, думаешь, пойдёт?

2019-01-01 18:57 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Так же вы можете [почитать документацию на английском](https://devcenter.heroku.com/), [обратиться к Хелпдеску за помощью](https://itsolschool.slack.com/messages/helpdesk) или [посмотреть на исходник
[Вот какое там есть видео](https://vimeo.com/147784643)

2019-01-01 18:58 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +- [Amazon Web Services](https://aws.amazon.com/ru/) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и сколько чего
Угу, ок

2019-01-01 18:59 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +web: gunicorn app:flask_app --log-file=- --log-level=debug
Хочу скрины файлов в реальном проекте в среде разработки

2019-01-01 19:00 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощьности или время
" мощьности"

2019-01-01 19:00 UTC, magicwolf9 commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
На мк ручками ребята создавали, хорошо бы хоть структуру скрином показать

2019-01-01 19:07 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Closure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
Я не могу им сказать "buildpack", они же не знают что такое. А так хоть геймеры поймут, что это что-то, сделанное заранее и работающее.

2019-01-01 19:07 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
Ручками это создавать - дело не благодарное. Тем более чтобы ручками создавать им нужно знать какую версию пакета использовать и в принципе учить немного синтаксис.

Структуру чего ты имеешь в виду?

2019-01-01 19:07 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +web: gunicorn app:flask_app --log-file=- --log-level=debug
Каких файлов? Не понимаю чего ты хочешь этим добиться.

2019-01-01 19:51 UTC, magicwolf9 submitted a review, later dismissed

2019-01-01 21:50 UTC, lariliel requested changes

2019-01-01 21:50 UTC, lariliel commented on tutorial/heroku_deployment.md
> +И так. Начнём с того, что такое облако. Облако - большое количество серверов, которыми занимается кто-то другой. Вам же на этих серверах можно делать что-то, что хотите сами, но по строгим правилам л
если это политика -- то зачем она здесь?

2019-01-01 21:51 UTC, lariliel commented on tutorial/heroku_deployment.md
> +
насколько это важно в контексте приложений ШИРа?

2019-01-01 21:56 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +
В принципе не очень важно на самом деле...

2019-01-01 21:58 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +И так. Начнём с того, что такое облако. Облако - большое количество серверов, которыми занимается кто-то другой. Вам же на этих серверах можно делать что-то, что хотите сами, но по строгим правилам л
```suggestion
И так. Начнём с того, что такое облако. Облако - большое количество серверов, которыми занимается кто-то другой. Вам же на этих серверах можно делать что-то, что хотите сами, но по строгим правилам хостера, чтобы котята не страдали.
```
Так лучше?

2019-01-01 21:58 UTC, lariliel commented on tutorial/heroku_deployment.md
> +VDS - выделенный виртуальный сервер. Если вам администратор даёт доступ к школьному серверу и даёт вам там погонять "машинку", то вы по сути пользуетесь VDS. Так же вы можете заплатить хостеру, и он
неа, пример про школьный сервер здесь про шаред-сервер, а не вдс/впс. вдс это про эксклюзивный доступ к машине внутри гипервизора или подсистемы FreeBSD Jail.

если затрагиваете слово вдс и проводите сравнение -- не лучше ли будет ИЛИ разобрать все варианты ИЛИ не затрагивать сравнения вообще?

2019-01-01 21:59 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Отличие состоит в том, что все облачные сервисы не дают доступ к серверу. Они принимают только "правильные" приложения. Специальные файлы с исходниками и настройками для приложения, иначае просто не
PaaS с вами не согласен.
Облака вполне дают доступ к настройкам серверов, просто не все, не всегда и не на всех тарифах.

2019-01-01 22:00 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- [Firebase](https://firebase.google.com/) - Платформа, которая даёт свой фремворк для взаимодействия. Если вы знаете что такое VM или какой-нибудь Node.js, то по сути вы просто пишите код для этой п
А что такое VM и что такое node.js? Что значит "просто вызывается"?

2019-01-01 22:00 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощности, или время
```suggestion
Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощности, или время работы на этих процессорах, или диски определённого объёма. Нам не нужно ничего самим трогать и думать о физической составляющей - этим занимается хостер.

 Большим компаниям это удобно потому, что если резко понадобится 300 новых серверов, например какой-то праздник, то всё что нужно - просто сказать хостеру: "Мне сегодня понадобятся 300 серверов, потому что сегодня будет праздник", и хостер в автоматическом режиме просто отдаст вам 300 серверов. А потом в таком же автоматическом режиме можно отдать эти сервера обратно, если они больше не нужны.
```

@lariliel всё же про то, почему эта технология используется гигантами рассказать надо бы, ведь это реальный мир, их надо как-то в него вливать

2019-01-01 22:02 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- [Amazon Web Services](https://aws.amazon.com/ru/) (AWS) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и скольк
AWS состоит из 70+ сервисов, где есть как IaaS решения, так и PaaS решения. То, что вы описываете, называется AWS ECS или Docker.

2019-01-01 22:03 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- [Amazon Web Services](https://aws.amazon.com/ru/) (AWS) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и скольк
Разделяете как? Это кстати очень гадкий вопрос, так как AWS как платформа для работы приложения -- очень своеобразная штука. Вы уверены, что вы хотите сообщать людям, что они должны разделить приложение на несколько нод?

2019-01-01 22:04 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Отличие состоит в том, что все облачные сервисы не дают доступ к серверу. Они принимают только "правильные" приложения. Специальные файлы с исходниками и настройками для приложения, иначае просто не
В данном случае рассматриваются далеко не все виды *aaS, так что упущение упоминания всех братьев не будет никаким образов влиять на следующее повествование.

2019-01-01 22:05 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Firebase](https://firebase.google.com/) - Платформа, которая даёт свой фремворк для взаимодействия. Если вы знаете что такое VM или какой-нибудь Node.js, то по сути вы просто пишите код для этой п
```suggestion
- [Firebase](https://firebase.google.com/) - Платформа, которая даёт свой фремворк для взаимодействия. Вы просто пишите _код для этой платформы_ и он вызывается платформой тогда, когда это надо, без лишних прогреваний или запуска виртуального сервера. _Оплата по количеству запросов_.
```

2019-01-01 22:07 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- [Heroku](https://heroku.com) - Обёртка над AWS. Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле Procfile как именно ваше приложение можно запу
Лол, не так оно работает. Внутри Амазона запущены виртуалки Хероку, AWS ECS не используется. Не уверен, что здесь вообще нужна привязка к Амазону. Иначе очень сложная к восприятию конструкция получается, много циклических определений.

2019-01-01 22:07 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +VDS - выделенный виртуальный сервер. Если вам администратор даёт доступ к школьному серверу и даёт вам там погонять "машинку", то вы по сути пользуетесь VDS. Так же вы можете заплатить хостеру, и он
В данном случае "сервер в школе" это и есть доступ к машине внутри гипервизора. Может вы даёте как-то иначе, но у нас в школе всё было именно так: мы говорили какую бы ось хотели, нам поднимали её на серваке и давали логин/пароль от админской учётки. Всё, далее мы делали всё в своём полёте.

2019-01-01 22:10 UTC, lariliel commented on tutorial/heroku_deployment.md
> + 1. Бесплатно: 570 часов работы каждый месяц (19 часов/день), 10k строчек в БД (Postgree) и Redis - достаточно неплохо для небольшого проекта
PostgreSQL, не Postgree. Redis -- не нужно командам кеширование.

2019-01-01 22:10 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Amazon Web Services](https://aws.amazon.com/ru/) (AWS) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и скольк
Про то, что приложение должно делиться на несколько нод - обязательно, потому что это особенность платформы, которую нужно учитывать при выборе.

Про то, какой конкретно сравнивать продукт - тут на самом деле вопрос действительно самый скользкий. Потому что я не являюсь инженером и не знаю какой конкретно из их продуктов за что отвечает. Так что если Вы можете дать ссылку, на максимально подходящий под описание их продукт, то я буду очень рад.

2019-01-01 22:11 UTC, lariliel commented on tutorial/heroku_deployment.md
> +2. Переносимость на свой сервер при необходимости - в отличии от Firebase вам не нужно будет из кода выпиливать половину специальных конструкций. В отличии от AWS, все необходимые вещи для запуска пр
Максимальный объём внимания человека -- 7+-2 объекта. Вот на этой строчке я уже забыл, что такое Firebase. Вы уверены, что вы хотите начать туториал с кучи терминов, не относящихся к цели текста?

2019-01-01 22:12 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Чатик
Дебатабле. Шаред-хостинг здесь лучше для всего, кроме ботов.

2019-01-01 22:12 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Heroku](https://heroku.com) - Обёртка над AWS. Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле Procfile как именно ваше приложение можно запу
```suggestion
- [Heroku](https://heroku.com) - Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле `Procfile` как именно ваше приложение можно запустить. _Оплата по времени работы_. (Сам Heroku использует для своих нужд AWS)
```

2019-01-01 22:12 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Чатик
Да и то, если хостинг правильный, т.е. с доступом к консоли -- то и для ботов тоже.

2019-01-01 22:14 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Amazon Web Services](https://aws.amazon.com/ru/) (AWS) - Вы создаёте своё приложение каким хотите, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и скольк
```suggestion
- [Amazon Web Services](https://aws.amazon.com/ru/ecs/) (AWS) - Вы создаёте своё приложение каким хотите и упаковываете его, разделяете его на небольшие кусочки (ноды) и отдаёте это всё Амазону. Он сам знает когда и сколько чего развернуть. _Оплата по времени работы и объёму*время хранения данных в хранилищах_.
```

2019-01-01 22:15 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
Облака Майкрософта, Амазона и Гугла сейчас +- одинаковы по возможностям. Дебатабле, что лучшее.

2019-01-01 22:15 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> + 1. Бесплатно: 570 часов работы каждый месяц (19 часов/день), 10k строчек в БД (Postgree) и Redis - достаточно неплохо для небольшого проекта
```suggestion
 1. Бесплатно: 570 часов работы каждый месяц (19 часов/день), 10k строчек в БД (PostgreSQL) и немножечко ещё - достаточно неплохо для небольшого проекта
```

2019-01-01 22:15 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
И я сильно не уверен, что у нас есть команды, которым нужны возможности, которые выходят за рамки Хероку.

2019-01-01 22:16 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Clojure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
так что такое пресет?

2019-01-01 22:17 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +2. Переносимость на свой сервер при необходимости - в отличии от Firebase вам не нужно будет из кода выпиливать половину специальных конструкций. В отличии от AWS, все необходимые вещи для запуска пр
```suggestion
2. Переносимость на свой сервер при необходимости - всё, что относится к Heroku - `Procfile`, всё остальное - ваше приложение, которое вполне можно будет завести руками на другом сервере.
```

2019-01-01 22:17 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Как я уже говорил, у Heroku есть разные "пресеты" для разных языков и платформ. Чтобы узнать, какой из этих "пресетов" использовать Heroku полагается на файлы-идентификаторы.
эту строчку бы повыше.

2019-01-01 22:17 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Чатик
Тут я немного не понял. Можно подробнее?

2019-01-01 22:19 UTC, lariliel commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
Консольные команды штука хорошая, только вы их для линукс даете. Перепишите на Power-Shell, пожалуйста, или CMD. Так как большинство будет пробовать вбить их в консоль винды и ГРУСТИТЬ

2019-01-01 22:19 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
АААААаааааааа

2019-01-01 22:20 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
Я чувствую себя святым Винсентом растерянным

2019-01-01 22:20 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
В мобильных приложениях реально легче будет использовать SDK от Firebase. Там и авторизация есть, и БД, и ещё много много всего, что может понадобится именно мобилкам. А на Хероку это всё придётся делать руками и затратиться на это больше времени.

2019-01-01 22:20 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
http://img1.reactor.cc/pics/post/растерянный-траволта-Винсент-лайфхак-песочница-3230219.jpeg

2019-01-01 22:21 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
Господи, что такое Торнадо, что такое Джанго, что такое гюникорн? Что такое сервер? Это тот сервер, который запускает облако в количестве 300 штук?

2019-01-01 22:21 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
Что такое uWSGI? И в чем отличие от нормальной WSGI?

2019-01-01 22:21 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
И главный вопрос: зачем это знать?

2019-01-01 22:22 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
А на счёт того, у кого круче облака по возможностям - тут вообще не надо. У них в принципе очень мало различий и чаще ведь выбор становится в том, какие сервисы будут использовать (мобилки или обязательно нужно использовать какой-нибудь asp с наворотам или 1C или ещё что-то). В нашем случае Firebase рекомендуется только из-за наличия SDK под мобилки.

2019-01-01 22:22 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- `--logl-level=debug` - выводить все логи, которые важнее/или debug
опечатка в --logl-level

2019-01-01 22:23 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- `--logl-level=debug` - выводить все логи, которые важнее/или debug
Кстати, что такое логи?

2019-01-01 22:23 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- `--logl-level=debug` - выводить все логи, которые важнее/или debug
Что значит "важнее/или"

2019-01-01 22:23 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- `--logl-level=debug` - выводить все логи, которые важнее/или debug
Что такое debug?

2019-01-01 22:23 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- `--log-file=-` - все логи нашего приложения выводить сразу в консоль
это куда?

2019-01-01 22:23 UTC, lariliel commented on tutorial/heroku_deployment.md
> +
Сюда бы скриншотики

2019-01-01 22:24 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Всё, круть! На доступна БД на 10k строк!
опечатка: Нам

2019-01-01 22:24 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Теперь мы каким-то магическим образом по этому адресу подключаемся к БД.
веет надежностью.

2019-01-01 22:25 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Теперь мы каким-то магическим образом по этому адресу подключаемся к БД.
кстати, этот гетенв куда писать?

2019-01-01 22:25 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Clojure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
В оригинале называются buildpack'ами. Это кучка скриптов, которая на себя берёт часть настроек под конкретную платформу и так же забирает некоторые необходимые для самого хероку вещи, типа загрузки всех зависимостей перед упаковкой в контейнер внутреннего формата.

Объяснять это на детском языке ещё сложнее, так что я сделал упор на то, что есть геймеры, которые знают что такое пресеты.

2019-01-01 22:27 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
через что?

Стандарт -- куча файлов настроек. Стандарт для приложений Майкрософта или "в стиле Майкрософта" -- отдельная база данных, занимающаяся только управлением настройками.
Гетенв -- это когда надо быстро и на коленке передать данные между хост-системой и нашим приложением.

2019-01-01 22:28 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
Если не верите про стандарт -- посмотрите, как внутри устроен Alfresco или MS Sharepoint

2019-01-01 22:28 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Как я уже говорил, у Heroku есть разные "пресеты" для разных языков и платформ. Чтобы узнать, какой из этих "пресетов" использовать Heroku полагается на файлы-идентификаторы.
В какой именно раздел? В этом разделе как раз самое место между "проблемой" и "решением"

2019-01-01 22:29 UTC, lariliel commented on tutorial/heroku_deployment.md
> +1. Все настройки (токены, пароли администраторов, любые данные для входа куда-нибудь) храните в переменных окуржения, теперь вы знаете как их получить, а в рядом с `DATABASE_URL` вполне можете так же
Вообще так лучше никогда не делать, кроме единственного случая получения данных из внешней системы в свою. И то, только тогда, когда нет желания написать нормальную интеграцию между хост-системой и вашим приложением. (что делается в подавляющем большинстве случаев)

2019-01-01 22:30 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. На самом деле приложение может быть и на Tornado, и на Django. У них у всех есть возможность использовать такую
```suggestion
Для начала нам нужно установить сервер, который будет запускать наше Flask приложение. Для этого мы установим специальный сервер [gunicorn](https://pypi.org/project/gunicorn/). Ну что же, установим его:
```

2019-01-01 22:30 UTC, lariliel commented on tutorial/heroku_deployment.md
> +1. Все настройки (токены, пароли администраторов, любые данные для входа куда-нибудь) храните в переменных окуржения, теперь вы знаете как их получить, а в рядом с `DATABASE_URL` вполне можете так же
(либо на интеграцию хост системы и нашего приложения вообще кладется)

2019-01-01 22:30 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- `--logl-level=debug` - выводить все логи, которые важнее/или debug
```suggestion
- `--log-level=debug` - выводить все сообщения от программы.
```

2019-01-01 22:31 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- `--log-file=-` - все логи нашего приложения выводить сразу в консоль
```suggestion
- `--log-file=-` - все сообщения выводить в консоль
```

Само по себе слово "консоль" им уже известно, они туда команды вбивали, чтобы gunicorn установить и чтобы requirements.txt создать.

2019-01-01 22:32 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Всё, круть! На доступна БД на 10k строк!
```suggestion
Всё, круть! Нам доступна БД на 10k строк!
```

2019-01-01 22:33 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
Или стандарт контейнирования настроек для распространения ПО на рабочие станции/новые сервера.
Там всегда либо куча файлов с настройками, либо отдельная база данных -- чаще всего в виде xml-файлов -- с тысячами опций.

2019-01-01 22:35 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Теперь мы каким-то магическим образом по этому адресу подключаемся к БД.
```suggestion
Теперь мы каким-то магическим образом по этому адресу подключаемся к БД. [Например вот так](https://github.com/BANOnotIT/helpdesk-tg-vk-bot/blob/master/app/db.py#L9-L23).
```

2019-01-01 22:36 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Всё! Теперь мы умеем забирать настройки для приложения из [переменных окружения](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D1
```suggestion
Всё! Теперь мы умеем забирать настройки для приложения из [переменных окружения](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D1%8B). [Вот как это делается у нас](https://github.com/BANOnotIT/helpdesk-tg-vk-bot/blob/master/config.py).
```

@lariliel вот куда писать getenv

2019-01-01 22:38 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
На счёт того, что куча файлов - я знаю что у каждой системы и программы свой стандарт настроек. Но в контейнерах стандарт один - либо стандартная рабочая настройка и небольшие изменения через ENV, либо ручная настройка через специальные подключаемые к контейнеру папки с настройками (в докере это называется секретами).

2019-01-01 22:39 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +1. Все настройки (токены, пароли администраторов, любые данные для входа куда-нибудь) храните в переменных окуржения, теперь вы знаете как их получить, а в рядом с `DATABASE_URL` вполне можете так же
Мы сейчас говорим про контейнерные приложения. У них все такие настройки берутся из окружения.

2019-01-01 22:43 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +
А скриншотиков чего конкретно не хватает?

2019-01-01 22:52 UTC, lariliel commented on tutorial/heroku_deployment.md
> +VDS - выделенный виртуальный сервер. Если вам администратор даёт доступ к школьному серверу и даёт вам там погонять "машинку", то вы по сути пользуетесь VDS. Так же вы можете заплатить хостеру, и он
круто, конечно, но у остальных будет не так. уровень виртуалки даже я не даю своим.

2019-01-01 22:53 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +VDS - выделенный виртуальный сервер. Если вам администратор даёт доступ к школьному серверу и даёт вам там погонять "машинку", то вы по сути пользуетесь VDS. Так же вы можете заплатить хостеру, и он
```suggestion
VDS/VPS - выделенный виртуальный сервер. На каком-то железном сервере поднимают виртуальную операционную систему и дают вам доступ к этой самой виртуальной системой. Внутри можно делать всё что угодно - на железный сервер никак это не повлияет.
```

2019-01-01 22:53 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Отличие состоит в том, что все облачные сервисы не дают доступ к серверу. Они принимают только "правильные" приложения. Специальные файлы с исходниками и настройками для приложения, иначае просто не
тогда надо конкретизировать, что такое облако в вашем туториале. иначе сейчас термин используется не так.

2019-01-01 22:54 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Чатик
ну готовый вебсайт на чем-нибудь вроде вордпресса проще просто на сервер закинуть и все.
что такое панелька администраторская -- я не понял.
чатик -- закинуть файлы на сервер через файлзиллу, опять же, проще, чем хероку.

2019-01-01 22:55 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Чатик
если бот написан на callback api -- то бот это просто сайт, к которому обращается вк. опять же, сайт проще всего файлами закинуть на сервер по фтп.

2019-01-01 22:56 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
круто, но сдк на мобилки есть у всех.

2019-01-01 22:57 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
и вы уверены, что командам нужны эти возможности?

2019-01-01 22:57 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
лимит внимания -- 7+-2 вещи.

2019-01-01 22:57 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Отличие состоит в том, что все облачные сервисы не дают доступ к серверу. Они принимают только "правильные" приложения. Специальные файлы с исходниками и настройками для приложения, иначае просто не
```suggestion
Отличие состоит в том, что все облачные сервисы не дают доступ к серверу. Они принимают только контейнеры - специальные файлы с исходниками и настройками для приложения и запускают их в автоматическом режиме без участия человека. Это нужно как раз для того, чтобы хостер мог без особых трудностей развернуть для вас 300 серверов за 10 секунд и точно так же за 2 секунды без лишних проблем отдать эти сервера другому человеку, если они ему будут нужнее.
```

2019-01-01 22:58 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Heroku - удобная платформа для разворачивания "правильных" приложений. Что такое облачная платформа и что такое "правильные" приложения - далее.
```suggestion
Heroku - удобная платформа для разворачивания контейнерных приложений. Что такое облачная платформа и что такое контейнеры - далее.
```

2019-01-01 22:58 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Clojure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
я геймер и я не знаю.

2019-01-01 22:58 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Так же платформа имеет "пресеты" для разных языков (Node.js, Python, Ruby, PHP, Java, Clojure, Scala, Go). Это всё из **бесплатных** пресетов, так же вы можете "докупить" пресет под что-то относитель
(в прошлом, правда)

2019-01-01 22:58 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Каждый сервис предлагает свои способы организации "правильных" приложений:
```suggestion
Каждый сервис предлагает свои способы организации контейнеризации:
```

2019-01-01 22:59 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Как я уже говорил, у Heroku есть разные "пресеты" для разных языков и платформ. Чтобы узнать, какой из этих "пресетов" использовать Heroku полагается на файлы-идентификаторы.
где был мой вопрос про "что такое пресет"

2019-01-01 22:59 UTC, lariliel commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
сделайте команды для винды, пожалуйста.

2019-01-01 23:00 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Бекэнд для мобильных приложений - тут лучше посмотреть в сторону [Firebase](https://firebase.google.com/), там для мобильных приложений очень много интересных плюшек предусмотрено.
То, что многим будет реально легче использовать готовое SDK от гугла вместо написания своих велосипедов - я уверен.

2019-01-01 23:00 UTC, lariliel commented on tutorial/heroku_deployment.md
> +
как подключать базу данных. просто интерфейс сайта, чтобы человек понимал, что это именно нужное окно.

2019-01-01 23:02 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
https://docs.microsoft.com/en-us/sccm/mdt/

2019-01-01 23:02 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
докер -- это вообще не о том.

2019-01-01 23:02 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Чатик
На счёт закинуть по ftp - вот далеко не проще автоматической развёртки. Да и ftp - прошлый век :D

Может тогда разделить всё это на 3 группы: можно, хорошо, не очень?

2019-01-01 23:03 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
докер это урезанная виртуальная машина, а я про разлив ПО из универсального контейнера по реальным хостам или виртуалкам.

2019-01-01 23:03 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
как только задачи становятся сложными, енв прекращает спасать.

2019-01-01 23:06 UTC, lariliel commented on tutorial/heroku_deployment.md
> +1. Все настройки (токены, пароли администраторов, любые данные для входа куда-нибудь) храните в переменных окуржения, теперь вы знаете как их получить, а в рядом с `DATABASE_URL` вполне можете так же
тогда это надо прописать, что применимо только к контейнерам. сейчас в тексте использовать енв рекомендуется для всех программ, что некорректно.

2019-01-01 23:07 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Buildpack - полуфабрикат для какого-то контейнера. В хероку в этих buildpack'ах спрятана разная магия по установке интерпретаторов языков, установке зависимостей и разного такого интересного.
```suggestion
Buildpack - полуфабрикат для какого-то контейнера. В хероку в этих buildpack'ах спрятана разная магия по установке интерпретаторов языков, установке зависимостей и разного такого интересного. Всё, что нам от всего этого нужно - что они бесплатные и делают грязную работу за нас, нам нужно только подкинуть туда свои исходники и немного настроить с помощью файла `Procfile`.
```

2019-01-01 23:07 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- `--log-file=-` - все сообщения выводить в консоль
всё ещё непонятно, что такое консоль в Хероку.

2019-01-01 23:09 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
На счёт сложных задач - не наш случай...

2019-01-01 23:10 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Все необходимые настройки приложению передаются через. Это скорее стандарт для всех приложений у больших компаний, так что при разработке приложения сразу советую все необходимые настройки (явки, пар
```suggestion
Все необходимые настройки приложению передаются через окружение или внешние файлы настроек. Так как Heroku не даёт закидывать внутрь себя произвольные файлы, то в нашем случае лучше всего использовать именно переменные окружения, тем более, что ими мы можем управлять из веб интерфейса.
```

2019-01-01 23:10 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +1. Все настройки (токены, пароли администраторов, любые данные для входа куда-нибудь) храните в переменных окуржения, теперь вы знаете как их получить, а в рядом с `DATABASE_URL` вполне можете так же
Чуть выше поменял формулировочку

2019-01-01 23:13 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- `--log-file=-` - все сообщения выводить в консоль
Есть у меня ощущение, что им вообще не надо объяснять что это такое. Потому что для того, чтобы логи работали им нужно будет немного поиграться с logging и другими питоновскими модулями.

2019-01-01 23:14 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
Я, честно говоря, не знаю как они будут выглядеть в PowerShell или CMD...

2019-01-01 23:17 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
Спрошу у ребят

2019-01-01 23:26 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +
```suggestion

![](https://prnt.sc/m1zr1t)

```

2019-01-01 23:39 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 install -f requirements.txt
```suggestion
pip3 install -r requirements.txt
```

2019-01-01 23:50 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
[Как ни странно, это сработает и для windows](https://docs.microsoft.com/ru-ru/visualstudio/python/managing-required-packages-with-requirements-txt?view=vs-2017)

2019-01-02 16:31 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +pip3 freeze > requirements.txt
@lariliel я выше сделал раздел про консоли

2019-01-03 11:20 UTC, lariliel commented on tutorial/heroku_deployment.md
> +И так. Начнём с того, что такое облако. Облако - большое количество серверов, которыми занимается кто-то другой. Вам же на этих серверах можно делать что-то, что хотите сами, но по строгим правилам х
чем отличается от шаред-хостинга? не понял, что такое облако.

2019-01-03 11:23 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Чем же это удобно для нас? Тем что нам не нужно руками трогать сервер и понимать как и какие провода соединять чтобы оно работало. Мы можем просто заказать процессоры определённой мощности, или время
всё ещё не понимаю, что такое облако. Зачем нам заказывать процессоры, если в прошлом предложении указано, что мы можем не трогать сервер и не знать, какие провода нужны?

2019-01-03 11:25 UTC, lariliel commented on tutorial/heroku_deployment.md
> + Большим компаниям это удобно потому, что если резко понадобится 300 новых серверов, например какой-то праздник, то всё что нужно - просто сказать хостеру: "Мне сегодня понадобятся 300 серверов, пото
всё ещё большой разницы с VPS/VDS/шаред не вижу. Там тоже можно масштабировать, просто библиотеки другие.

Мне кажется вы пытаетесь объяснить противоположные вещи: вы начинаете с AWS EC2, а весь туториал у вас про AWS ECS, условно говоря. Я пишу терминами Амазона, так как работаю с Амазоном, но суть примерно та же. Я не уверен, что вам надо начинать так глубоко.

2019-01-03 11:27 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Отличие состоит в том, что все облачные сервисы не дают доступ к серверу. Они принимают только контейнеры - специальные файлы с исходниками и настройками для приложения и запускают их в автоматическо
А вот здесь вы с описания EC2 резко перешли на ECS, хотя это совсем разные технологии. Облако -- это И IaaS, дающий доступ VPS/VDS, И PaaS, дающий просто выполнять приложения.

2019-01-03 11:28 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- [Heroku](https://heroku.com) - Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле `Procfile` как именно ваше приложение можно запустить. _Оплата
Это здорово, но вы пишете туториал по Хероку. Возможности человеческого внимания -- 7+-2 объекта в краткосрочной памяти, вы уверены, что хотите в туториале по конкретной системе тратить возможности мозга читателей на что-то иное?

У нас нет команд, которые пишут на Руби/Ноде. Вы действительно хотите их указывать как первые примеры? Что вы хотите получить этим упоминанием?

2019-01-03 11:30 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Сервер для чего-то, что должно работать 24/7, например стриминговый сервис для хомячков
Кто такие хомячки? Так вообще пару лет назад очень уничижительно называли с экранов госсми школьников-поклонников Навального. Вы _уверены_, что вы хотите этих ассоциаций?

2019-01-03 11:31 UTC, lariliel commented on tutorial/heroku_deployment.md
> +И так, как же работает Heroku. В отличии от AWS, ваше приложение не работает всё время, оно включается тогда, когда к нему пришёл какой-то запрос и работает после этого ещё 30 минут, вдруг ещё придёт
Вы про какой AWS говорите? Там есть сервисы, которые работают по вызову, как и Хероку. Вы уверены, что вы хотите нагружать возможности мозга читателя сравнениями?

2019-01-03 11:31 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Так же платформа имеет buildpack для разных языков (Node.js, Python, Ruby, PHP, Java, Clojure, Scala, Go). Это всё из **бесплатных** buildpack'ов, так же вы можете "докупить" под что-то относительно
Что такое билдпак?

2019-01-03 11:31 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Минусы - приложение запускается на самом деле не очень быстро, так что может возникунть проблема того, что пользователь будет минутку другую ждать пока ему придёт ответ от нашего сервера, но зато ост
Кто такие хомячки?

2019-01-03 11:32 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Buildpack - полуфабрикат для какого-то контейнера. В хероку в этих buildpack'ах спрятана разная магия по установке интерпретаторов языков, установке зависимостей и разного такого интересного. Всё, чт
что такое полуфабрикат? что такое контейнер?

2019-01-03 11:33 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Но часто вполне хватает Python + Postgree + Redis.
PostgreSQL и удалите уже Редис, ей богу, он не нужен командам.

2019-01-03 11:33 UTC, lariliel commented on tutorial/heroku_deployment.md
> +1. Запустите свою _консоль_
как?

2019-01-03 11:34 UTC, lariliel commented on tutorial/heroku_deployment.md
> +2. Введите `pip3 --version`
если питон установлен с настройками по умолчанию, то ни python, ни pip не прописаны в PATH и команда не заработает.

2019-01-03 11:34 UTC, lariliel commented on tutorial/heroku_deployment.md
> +- Приложение является блогом
Почему блог? вы же на мк рассказывали бота для телеги?

2019-01-03 11:35 UTC, lariliel commented on tutorial/heroku_deployment.md
> +3. У вас в системе в принципе python установлен неправильно. Обратитесь с этим вопросом к [хелпдеску](https://itsolschool.slack.com/messages/helpdesk)
как понять, какую команду использовать?

2019-01-03 11:35 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Как я уже говорил, у Heroku есть разные buildpack'и для разных языков и платформ. Чтобы узнать, какой из этих "пресетов" использовать, Heroku полагается на файлы-идентификаторы.
так пресет или билдпак?

2019-01-03 11:35 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Как я уже говорил, у Heroku есть разные buildpack'и для разных языков и платформ. Чтобы узнать, какой из этих "пресетов" использовать, Heroku полагается на файлы-идентификаторы.
что за файлы-идентификаторы?

2019-01-03 11:36 UTC, lariliel commented on tutorial/heroku_deployment.md
> +Давайте сделаем файл-индикатор. В файле `requirements.txt` по договорённости всех разработчиков должны храниться названия и версии всех пакетов, которые необходимы для работы приложения. Создать этот
файл-индикатор или файл-идентификатор?

2019-01-03 14:25 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- [Heroku](https://heroku.com) - Вы создаёте приложение на любимом языке (Node.js, Ruby, PHP, Python) и рассказываете в небольшом файле `Procfile` как именно ваше приложение можно запустить. _Оплата
На счёт ноды и руби - могут появится такие, которые пишут, в позопрошлом году я писал на ноде.

Можно заменить на страницу, где просто показаны все эти яп, пусть сами интересуются.

2019-01-03 14:27 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Приложение является блогом
Очепятка.

```suggestion
- Приложение является ботом
```

2019-01-03 14:28 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +2. Введите `pip3 --version`
Такой сценарий описан ниже.

2019-01-03 14:28 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +3. У вас в системе в принципе python установлен неправильно. Обратитесь с этим вопросом к [хелпдеску](https://itsolschool.slack.com/messages/helpdesk)
Все подряд. Поэтому и написано, что может быть несколько сценариев и выходов из них.

2019-01-03 14:28 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Как я уже говорил, у Heroku есть разные buildpack'и для разных языков и платформ. Чтобы узнать, какой из этих "пресетов" использовать, Heroku полагается на файлы-идентификаторы.
```suggestion
Как я уже говорил, у Heroku есть разные buildpack'и для разных языков и платформ. Чтобы узнать, какой из этих buildpack'ов использовать, Heroku полагается на файлы-идикаторы.
```

2019-01-03 14:39 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +- Сервер для чего-то, что должно работать 24/7, например стриминговый сервис для хомячков
"Я хотел сказать именно то, что написал")

В прошлом году был проект на ардуине про хомячков, вот я его и вспомнил. 

А ассоциации... К любому слову можно найти такие ассоциации, так что пусть лучше искореняют ассоциации с обычными словами, а не обычные слова.

2019-01-03 14:40 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Минусы - приложение запускается на самом деле не очень быстро, так что может возникунть проблема того, что пользователь будет минутку другую ждать пока ему придёт ответ от нашего сервера, но зато ост
Выше ответил

2019-01-03 14:58 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +И так, как же работает Heroku. В отличии от AWS, ваше приложение не работает всё время, оно включается тогда, когда к нему пришёл какой-то запрос и работает после этого ещё 30 минут, вдруг ещё придёт
```suggestion
И так, как же работает Heroku.

Ваше приложение не работает всё время, оно включается тогда, когда к нему пришёл какой-то запрос и работает после этого ещё 30 минут, вдруг ещё кто-то придёт. И время считается именно за включенное приложение.
```

2019-01-03 15:00 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Buildpack - полуфабрикат для какого-то контейнера. В хероку в этих buildpack'ах спрятана разная магия по установке интерпретаторов языков, установке зависимостей и разного такого интересного. Всё, чт
Контейнеры описаны выше по тексту.

2019-01-03 15:01 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Но часто вполне хватает Python + Postgree + Redis.
```suggestion
Но часто вполне хватает Python + PostgreSQL.
```

2019-01-03 21:48 UTC, lariliel commented on tutorial/heroku_deployment.md
> +1. Запустите свою _консоль_
просто запуск павершела в первый раз это то ещё удовольствие. хотя можно оставить на сообразительность команды, наверное.

2019-01-03 21:48 UTC, lariliel commented on tutorial/heroku_deployment.md
> +3. У вас в системе в принципе python установлен неправильно. Обратитесь с этим вопросом к [хелпдеску](https://itsolschool.slack.com/messages/helpdesk)
это бы прописать, что "попробуем такие три действия"

2019-01-04 00:37 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Если система сказала что-то плохое, а не `pip *.*.* from ***`, то есть несколько вариантов развития событий:
```suggestion
Если система сказала что-то плохое, а не `pip *.*.* from ***`, то есть несколько вариантов развития событий. Давайте пройдёмся по каждому:
```

2019-01-04 00:38 UTC, BANOnotIT commented on tutorial/heroku_deployment.md
> +Давайте сначала определимся, где мы находимся. Все последующие инструкции работают в 2 разных средах: сайт Heroku, консоль. Консоль может быть либо _стандартная_ в Linux, либо _PowerShell_, если Вы р
```suggestion
Давайте сначала определимся, где мы находимся. Все последующие инструкции работают в 2 разных средах: сайт Heroku, консоль. Консоль может быть либо _стандартная_ в Linux, либо [_PowerShell_](https://remontka.pro/run-windows-powershell/), если Вы работаете из под Windows.
```
@lariliel вот ссылка на то, как ps запускается

2019-01-04 11:22 UTC, merged