Edited techs
itsolschool/itsolschool.github.io pull request #16
Opened 2018-11-06 22:17 UTC by magicwolf9

2018-11-06 22:24 UTC, BANOnotIT requested changes

2018-11-06 22:24 UTC, BANOnotIT commented on tech-graph.md
> +- [Django](https://www.djangoproject.com/) - Фреймворк, в котором есть почти всё и сразу. (Въехать значительно сложнее, чем во Flask)
Мне не кажется правильной формулировка сложнее , кому-то сложнее по всему интернету себе искать модули и orm. Я старался без оценочных писать)

2018-11-06 22:24 UTC, BANOnotIT commented on tech-graph.md
> -- [Socket.io](https://socket.io/) - Библиотека для работы с WebSocket.
Вообще может понадобиться для часиков , но это вполне можно и потом рассказать, так что да. Тут не нужно, а вот в challenge можно

2018-11-06 22:27 UTC, magicwolf9 commented on tech-graph.md
> +- [Django](https://www.djangoproject.com/) - Фреймворк, в котором есть почти всё и сразу. (Въехать значительно сложнее, чем во Flask)
Мы изначально говорили о фласке как о фреймворке для тех, кто к django еще морально и физически не готов, поэтому раз они тут на одном уровне стоят пусть хоть так будут разграничены. Но если беспокоит именно формулировка, то могу поменять, только мне нужно вектор задать)

2018-11-06 22:28 UTC, magicwolf9 commented on tech-graph.md
> -- [Socket.io](https://socket.io/) - Библиотека для работы с WebSocket.
Более узконаправленная штука на фоне остального, сомневаюсь что вообще в рекомендациях нужно затрагивать

2018-11-07 14:19 UTC, BANOnotIT requested changes

2018-11-07 14:19 UTC, BANOnotIT commented on tech-graph.md
> -- [Socket.io](https://socket.io/) - Библиотека для работы с WebSocket.
Да, возможно ты прав, это можно всё же посоветовать и словами, если кому-то понадобится.

2018-11-07 14:19 UTC, BANOnotIT commented on tech-graph.md
> +- [Django](https://www.djangoproject.com/) - Фреймворк, в котором есть почти всё и сразу. (Въехать значительно сложнее, чем во Flask)
Мне просто не нравится формулировка "сложнее". Он не сложнее, он как раз более подходит под понятие фреймворк, чем фласк, так как предоставляет свою точку зрения к организации кода и всего. Фласк же именно каркасный, то есть просто даёт возможность раскидывать запросы по разным функциям в зависимости от url и обрабатывать их.

Я бы сказал что джанга именно комплексное решение, которое решает за разраба сразу много задач, фласк же является одной из деталей конструктора...

2018-11-07 20:32 UTC, magicwolf9 commented on tech-graph.md
> +- [Django](https://www.djangoproject.com/) - Фреймворк, в котором есть почти всё и сразу. (Въехать значительно сложнее, чем во Flask)
Это не сделает понятным то, что новичкам лучше не лезть. Если так можно просто вынести в challenge

2018-11-07 20:49 UTC, BANOnotIT commented on tech-graph.md
> +- [Django](https://www.djangoproject.com/) - Фреймворк, в котором есть почти всё и сразу. (Въехать значительно сложнее, чем во Flask)
Хм... Кажется мы добрались до сути проблемы. Мы считаем, что фреймворки из разных весовых категорий.

Давай тогда думать. Я лично считаю, что лучше когда модели, темплейты, роуты - всё работает из коробки. Ты считаешь само их наличие сложным.

PS. По сути во фласке они тоже будут использовать темплейты, роуты и модели, вот только искать их в других местах и совокуплять друг с другом тоже будут сами, в джанге же оно всё из коробки.

2018-11-07 21:43 UTC, BANOnotIT approved these changes

2018-11-07 21:44 UTC, merged