Внесение стека в словарь
itsolschool/itsolschool.github.io pull request #6
Opened 2018-10-31 22:06 UTC by Khazbs

А также комментирование "кек"-ов

2018-11-01 23:08 UTC, magicwolf9 requested changes

2018-11-01 23:08 UTC, magicwolf9 commented on dictionary.md
> +[//]: # Кек
Полагаю Миша оставил пометки (кек) тип чтоб глянули эти определения и предложили лучше, в файле это не нужно

2018-11-01 23:10 UTC, Khazbs commented
Да, но пока эти определения не будут пофикшены, "кек" может в том или ином ином видем там присутствовать. Как комментарии — вполне емко.02:08, November 2, 2018, Evgenii Kukhta <notifications@github.com>:@magicwolf9 requested changes on this pull request.



In dictionary.md:
>  
-Бизнес-процесс — это набор работ, с помощью которых будет создаваться продукт.
-(кек)
-Бизнес-логика - это представление того, как бизнес-процесс должен выглядеть в рамках продукта
-(кек)
-Классы - модель какого-то предмета из реального(и не только) мира, описывающая его свойства и функции. Например, у автомобиля свойствами будет его марка, цвет и др, а функцией будет возможность ехать, открывать двери и тп
+Бизнес-процесс - это набор работ, с помощью которых будет создаваться продукт.
+[//]: # Кек

Полагаю Миша оставил пометки (кек) тип чтоб глянули эти определения и предложили лучше, в файле это не нужно

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sent from Yandex.Mail for mobile

2018-11-01 23:12 UTC, magicwolf9 commented
Пусть тогда лучше pr повисит, пока Миша не поправит определения. Когда готово все будет, тогда в мастер и помержим

2018-11-03 00:06 UTC, BANOnotIT requested changes
Так же нужно определение MVP и MVC. Второе нам понадобится в объяснениях, а вот первое используют и другие люди.

2018-11-03 00:06 UTC, BANOnotIT commented on dictionary.md
> +Стек (стек вызовов) - это история выполнения компьютером подпрограмм.
Так же это способ хранения данных
```suggestion
Стек  -
[1] ~: способ хранения данных в виде "стопки" (например, тарелок). Взять тарелку снизу стопки не получится. В программировании используется из-за скорости доступа к элементам "стопки";
[2] ~ вызовов: это история выполнения компьютером подпрограмм;
[3] ~ технологий: это список библиотек или фреймворков, используемых в проекте.
```

2018-11-03 00:06 UTC, BANOnotIT commented on dictionary.md
> -Бизнес-логика - это представление того, как бизнес-процесс должен выглядеть в рамках продукта
Я всё же отношусь к тому числу людей, которые под бизнес-логикой понимают совокупность фич продукта, обеспечивающих его минимальную работоспособность.

2018-11-03 21:57 UTC, BANOnotIT commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать словарь терминов, с простым пояснением](https://trello.com/c/LOTjrys2/10-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C-%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2-%D1%81-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC-%D0%BF%D0%BE%D1%8F%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC)

2018-11-04 16:18 UTC, Khazbs commented on dictionary.md
> -Бизнес-логика - это представление того, как бизнес-процесс должен выглядеть в рамках продукта
Я вообще отношусь к тому числу людей, которые не считают, что эти термины могут пригодиться.

2018-11-04 16:20 UTC, Khazbs commented
А где сам Миша-то*

2018-11-07 21:49 UTC, BANOnotIT commented on dictionary.md
> +Модуль - программа, записанная в отдельный файл, из которой можно вызывать какие-либо функции.
```suggestion
Модуль - файл, в котором хранится часть программы. Призван сделать чтение кода программы удобнее и понятнее за счёт разделение большого объёма строк на группы по назначению (авторизация, работа с файлами, работа с БД) и вынесение их в отдельный файл.
```

2018-11-07 23:42 UTC, BANOnotIT commented on dictionary.md
> +Фича - какая-либо фишка продукта влияющая на возможности пользователя
```suggestion
Фича - какая-либо фишка продукта влияющая на возможности пользователя.
```

2018-11-07 23:43 UTC, BANOnotIT commented on dictionary.md
> +Фича - какая-либо фишка продукта влияющая на возможности пользователя
```suggestion
Фича - какая-либо фишка продукта влияющая на возможности пользователя. В основном это дополнительный функционал, не влияющий на главную цель продукта.
```

2018-11-07 23:43 UTC, BANOnotIT commented on dictionary.md
> +Киллер фича - фича, которая есть только у данного продукта и которая дает ему преимущества на рынке
А нужно ли оно тута?

2018-11-07 23:44 UTC, magicwolf9 commented on dictionary.md
> +Киллер фича - фича, которая есть только у данного продукта и которая дает ему преимущества на рынке
Вообще используется в разговоре, пусть будет

2018-11-07 23:45 UTC, magicwolf9 requested changes
Бизнес-логика

2018-11-07 23:45 UTC, magicwolf9 commented on dictionary.md
> +Бизнес-логика - это описание отношений, поведения между элементами или процессами предметной области, которая реализуется в приложении.
Как это сюда попало, мы ведь все от этого плевались и придумали другое

2018-11-07 23:46 UTC, BANOnotIT requested changes

2018-11-07 23:46 UTC, BANOnotIT commented on dictionary.md
> +API - это такой “ящик”, на который разработчик может отправлять запросы и получать в ответ данные необходимые для работы. Примеры: Yandex.Maps API, VK API
```suggestion
API (Интерфейс Взаимодействия Приложений) - набор правил и команд, позволяющий одной программе управлять другой. Чаще используется для получения информации, которая есть только у "другой" программы. Примеры: Yandex.Maps API, VK API
```

2018-11-11 18:28 UTC, BANOnotIT submitted a review, later dismissed

2018-11-11 18:28 UTC, BANOnotIT commented on dictionary.md
> -Бизнес-логика - это представление того, как бизнес-процесс должен выглядеть в рамках продукта
Не пригодились )

2018-11-11 18:28 UTC, BANOnotIT commented on dictionary.md
> +Объект (экземпляр класса) - частный пример класса, то есть автомобиль конкретной марки и конкретного цвета
```suggestion
Объект (экземпляр класса) - частный пример класса, то есть автомобиль конкретной марки и конкретного цвета, который может ездить и поворачивать.
```

2018-11-22 23:14 UTC, magicwolf9 submitted a review, later dismissed

2018-11-24 11:19 UTC, Khazbs commented on dictionary.md
> +Модуль - файл, в котором хранится часть программы. Призван сделать чтение кода программы удобнее и понятнее за счёт разделение большого объёма строк на группы по назначению (авторизация, работа с фай
за счет разделени*я*

2018-11-24 11:19 UTC, Khazbs commented on dictionary.md
> +Фича - какая-либо фишка продукта влияющая на возможности пользователя. В основном это дополнительный функционал, не влияющий на главную цель продукта.
продукта, влияющая

2018-11-24 15:49 UTC, magicwolf9 approved these changes

2018-11-24 15:50 UTC, merged