Рихтовка алгоритма декомпозиции
itsolschool/itsolschool.github.io pull request #8
Opened 2018-11-03 22:13 UTC by BANOnotIT

Добавил предисловие к алгоритму, добавил несколько примеров, показал, где конкретно нужно его включать.

В общем сделал то, что предложил Петя

2018-11-03 22:14 UTC, BANOnotIT commented
![](https://github.trello.services/images/mini-trello-icon.png) [Алгоритм дробления задачи на подзадачи](https://trello.com/c/KyvlKeMb/8-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC-%D0%B4%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8-%D0%BD%D0%B0-%D0%BF%D0%BE%D0%B4%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8)

2018-11-05 00:48 UTC, magicwolf9 commented
Раз алгоритм это последовательность шагов, то и в примерах применение алгоритма стоит писать пошагово, чтобы было нагляднее

2018-11-05 00:49 UTC, magicwolf9 requested changes
Раз алгоритм это последовательность шагов, то и в примерах применение алгоритма стоит писать пошагово, чтобы было нагляднее

2018-11-05 13:51 UTC, BANOnotIT commented
@magicwolf9 мне сложно по этому алгоритму идти, у меня как-то сразу делится на мелкие задачки, я поэтому и написал входные данные и выходные.

2018-11-06 21:18 UTC, magicwolf9 approved these changes

2018-11-06 21:33 UTC, merged