Добавлен why.md о том, зачем нужно учиться поиску
itsolschool/itsolschool.github.io pull request #9
Opened 2018-11-04 15:57 UTC by Khazbs

2018-11-04 15:59 UTC, Khazbs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Написать поясняющий текст "зачем нужно учиться искать информацию в интернете"](https://trello.com/c/JqhipbPo/17-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE%D1%8F%D1%81%D0%BD%D1%8F%D1%8E%D1%89%D0%B8%D0%B9-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%B7%D0%B0%D1%87%D0%B5%D0%BC-%D0%BD%D1%83%D0%B6%D0%BD%D0%BE-%D1%83%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D0%B8%D1%81%D0%BA%D0%B0%D1%82%D1%8C-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E-%D0%B2-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82%D0%B5)

2018-11-05 00:46 UTC, magicwolf9 commented
Крутой текст. Еще можно добавить часть, которая бы показывала, что это не так просто как кажется, а то при прочтении могут подумать "как хорошо, что я и так это уже умею, это ведь легко"

2018-11-05 13:27 UTC, BANOnotIT commented
Хороший текст. Цель понятна и хорошо донесена. Есть только 1 просьба: поменьше *курсива*)

2018-11-06 15:09 UTC, magicwolf9 requested changes
Крутой текст. Еще можно добавить часть, которая бы показывала, что это не так просто как кажется, а то при прочтении могут подумать "как хорошо, что я и так это уже умею, это ведь легко"

2018-11-07 23:34 UTC, BANOnotIT approved these changes

2018-11-07 23:36 UTC, magicwolf9 approved these changes

2018-11-07 23:37 UTC, merged